dist: bionic

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel

script:
  - bazel version
  - cd examples
  # build examples as a means of testing
  - bazel build --jobs 2 //antlr2/Cpp/... //antlr2/Calc/... //antlr2/Python/... //antlr3/Cpp/... //antlr3/Java/... //antlr3/Python2/... //antlr3/Python3/... //antlr4/Cpp/... //antlr4/Go/... //antlr4/Java/... //antlr4/Python2/... //antlr4/Python3/...
  - cd antlr4-opt
  - bazel build --jobs 2 //...
  - cd ../..
  - bazel test --jobs 2 --test_output=errors //...
  - bazel shutdown

language: java

